version: '3.8'

services:

  consul-server:
    image: hashicorp/consul:1.11.4
    container_name: consul-server
    restart: always
    volumes:
      - ./test/server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

  consul-client-a:
    image: hashicorp/consul:1.11.4
    container_name: consul-client-a
    restart: always
    networks:
      - consul
    command: "agent -node=client-a -join=consul-server -encrypt aPuGh+5UDskRAbkLaXRzFoSOcSM+5vAK+NEYOWHJH7w="

  consul-client-b:
    image: hashicorp/consul:1.11.4
    container_name: consul-client-b
    restart: always
    networks:
      - consul
    command: "agent -node=client-b -join=consul-server -encrypt aPuGh+5UDskRAbkLaXRzFoSOcSM+5vAK+NEYOWHJH7w="
    depends_on:
      - consul-server

  cts:
    image: hashicorp/consul-terraform-sync:latest
    container_name: cts
    restart: always
    volumes:
      - ./test/cts-config.hcl:/consul-terraform-sync/config/cts-config.hcl:rw
      - ./:/dnsimple-consul:ro
    networks:
      - consul
    ports:
      - "8558:8558"
    command: "--config-file=/consul-terraform-sync/config/cts-config.hcl"
    depends_on:
      - consul-server

networks:
  consul:
    driver: bridge
